project:
  type: book
  output-dir: docs

book:
  title: "Online Retail Transaction Data"
  author: "Choo Jian Yuan"
  date: "08/06/2025"
  chapters:
    - index.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt

editor: visual

